config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  root to: "home#index"
  resources :restaurants
  resources :pages
  resources :contact
  resources :payment

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  belongs_to :restaurant

  has_many :order_foods
  has_many :orders, through: :order_foods

  mount_uploader :avatar, AvatarUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_foods
  has_many :foods, through: :order_foods
end

app/models/order_food.rb
class OrderFood < ApplicationRecord
  belongs_to :order
  belongs_to :food
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1, moderator: 2, editor: 3, vip: 4, banned: 5 }
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  layout 'home'
  def index
  end

  def new
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :quantity, :price, :category_id, :restaurant_id, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    update_from_param(params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    update_from_param(params)
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
  def set_order
      @order = Order.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def order_params
      params.require(:order).permit(:customer_id, :total_price, :quantity)
  end

  def update_from_param(params)
    food_ids = params[:order][:food_ids].reject(&:blank?)
    foods = Food.where(id: food_ids)
    @order.foods = foods

    # food_ids.each do |food_id|
    # order_food = OrderFood.where(order_id: @order.id, food_id: food_id).first_or_create
    #   order_food.quantity = 100
    #   order_food.total_price = 1000
    #   order_food.save
    # end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'home'
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <title>PosHungbx</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="footer-offset has-navbar-vertical-aside navbar-vertical-aside-show-xl">
  <%= render 'shared/header' %>
  <%= render 'shared/aside' %>
  <%= render 'shared/message' %>

  <main id="content" role="main" class="main">
    <div class="content container-fluid">
      <%= yield %>
    </div>
  </main>

  <%= yield :javascripts %>
  <%= javascript_include_tag asset_path("/js/ckeditor.js", skip_pipeline: true) %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
  <title>PosHungbx</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="utf-8">
  <meta content="Chernyh Mihail" name="author">
  <meta content="Spedito - All in one place" name="description">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="HandheldFriendly" content="true">
  <meta name="format-detection" content="telephone=no">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">

  <%= javascript_pack_tag 'darkmode' %>
  <%= javascript_pack_tag 'fontawesome' %>
  <%= javascript_pack_tag 'jquery' %>
  <%= javascript_pack_tag 'libs' %>

  <%= javascript_pack_tag 'uikit' %>
  <%= javascript_pack_tag 'uikit-icons' %>
  <%= javascript_pack_tag 'main' %>

  <%= stylesheet_link_tag 'home' %>

</head>
    <%= yield %>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <%= display_meta_tags site: 'Fulfillment Hub' %>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= yield :stylesheets %>

  <%= favicon_link_tag %>
</head>

<body class="footer-offset has-navbar-vertical-aside navbar-vertical-aside-show-xl">

<%= yield %>

<%= yield :javascripts %>
</body>
</html>

app/views/shared/_aside.html.erb
<aside class="js-navbar-vertical-aside navbar navbar-vertical-aside navbar-vertical navbar-vertical-fixed navbar-expand-xl navbar-bordered navbar-dark navbar-vertical-aside-initialized">
  <div class="navbar-vertical-container">
    <div class="navbar-vertical-footer-offset pb-0">
      <div class="navbar-brand-wrapper justify-content-between">
        <!-- Logo -->

        <a class="navbar-brand" href="<%= root_path %>" aria-label="Front">
          <%#= image_tag "logo.png", class: "navbar-brand-logo", alt: "Logo", style: "height: 40px; width: 40px; min-width: unset" %>
          <%#= image_tag "logo.png", class: "navbar-brand-logo-mini", alt: "Logo", style: "height: 40px; width: 40px; min-width: unset" %>
        </a>

        <!-- End Logo -->

        <!-- Navbar Vertical Toggle -->
        <button type="button" class="js-navbar-vertical-aside-toggle-invoker navbar-vertical-aside-toggle btn btn-icon btn-xs btn-ghost-dark">
          <i class="tio-clear tio-lg"></i>
        </button>
        <!-- End Navbar Vertical Toggle -->
      </div>

      <!-- Content -->
      <div class="navbar-vertical-content">
        <ul class="navbar-nav navbar-nav-lg nav-tabs">

          <li class="nav-item">
            <small class="nav-subtitle" title="Pages">Admin</small>
            <small class="tio-more-horizontal nav-subtitle-replacer"></small>
          </li>

          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= restaurants_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%= fa_icon('coffee', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Restaurants</span>
            </a>
          </li>
          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= categories_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%= fa_icon('clipboard-list', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Categories</span>
            </a>
          </li>
          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= foods_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%= fa_icon('hamburger', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Foods</span>
            </a>
          </li>
          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= customers_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%= fa_icon('user-friends', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Customers</span>
            </a>
          </li>
          <li class="nav-item ">
            <a class="js-nav-tooltip-link nav-link " href="<%= orders_path %>" title="" data-placement="left" data-original-title="Layouts">
              <%= fa_icon('file-alt', class: "nav-icon") %>
              <span class="navbar-vertical-aside-mini-mode-hidden-elements text-truncate">Orders</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- End Content -->
    </div>
  </div>
</aside>

app/views/shared/_footer-home.html.erb
<footer class="page-footer">
  <div class="page-footer__top">
    <div class="uk-container">
      <div class="page-footer__logo">
        <div class="logo"> <a class="logo__link" href="<%= root_path %>"><%= image_tag("logo.png", :alt => "logo", class: "logo__img") %></a></div>
      </div>
      <div class="page-footer__contacts">
        <div class="contact-item-box">
          <div class="contact-item-box__title">Địa chỉ </div>
          <div class="contact-item-box__value">Lầu 70, landmark 81, Bình Thạnh<br> Thành phố Hồ Chí Minh</div>
        </div>
        <div class="contact-item-box">
          <div class="contact-item-box__title">Giờ mở cửa</div>
          <div class="contact-item-box__value">Mon – Sat: 10:00 AM – 11:30 PM<br> Sun: 9:00 AM – 4:00 PM</div>
        </div>
        <div class="contact-item-box">
          <div class="contact-item-box__title">Liên hệ</div>
          <div class="contact-item-box__value">Email: <a href="#">bxhunga3@gmail.com</a><br> Phone: <a href="tel:3205448749">320-544-8749</a></div>
        </div>
      </div>
    </div>
  </div>
  <div class="page-footer__bottom">
    <div class="uk-container">
      <div class="page-footer__social">
        <ul class="social">
          <li class="social-item"><a class="social-link" href="#"><i class="fab fa-twitter"></i></a></li>
          <li class="social-item"><a class="social-link" href="#"><i class="fab fa-facebook-f"></i></a></li>
          <li class="social-item"><a class="social-link" href="#"><i class="fab fa-linkedin-in"></i></a></li>
          <li class="social-item"><a class="social-link" href="#"><i class="fab fa-google-plus-g"></i></a></li>
          <li class="social-item"><a class="social-link" href="#"><i class="fab fa-youtube"></i></a></li>
        </ul>
      </div>
      <div class="page-footer__copy"><span>© Copyrights 2020 Spedito. All rights reserved.</span><a href="#">Terms and Conditions</a></div>
    </div>
  </div>
  <div id="offcanvas" data-uk-offcanvas="overlay: true">
    <div class="uk-offcanvas-bar"><button class="uk-offcanvas-close" type="button" data-uk-close=""></button>
      <div class="uk-margin-top">
        <ul class="uk-nav">
          <li><a href="#">Home</a></li>
          <li><a href="#">Order Online</a></li>
          <li><a href="#">Our Menu</a></li>
          <li><a href="#">Feedback</a></li>
          <li><a href="#">Contact us</a></li>
        </ul>
      </div>
      <hr class="uk-margin">
      <ul class="uk-nav uk-nav-parent-icon" data-uk-nav>
        <li><a href="#">Bún</a></li>
        <li><a href="#">Cơm - xôi </a></li>
        <li><a href="#">Cháo - phở - hủ tiếu</a></li>
        <li><a href="#">Bánh</a></li>
        <li><a href="#">Đồ uống</a></li>
      </ul>
      <hr class="uk-margin">
      <div class="uk-margin-bottom">
        <div class="block-with-phone"><%= image_tag("icons/delivery.png", :alt => "delivery")%>
          <div> <span>For Delivery, Call us</span><a href="tel:13205448749">1-320-544-8749</a></div>
        </div>
      </div>
    </div>
  </div>
  <div class="uk-flex-top" id="callback" data-uk-modal="">
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical">
      <button class="uk-modal-close-default" type="button" data-uk-close=""></button>
      <p></p>
    </div>
  </div>
  <div class="uk-modal-full uk-modal" id="modal-full" data-uk-modal>
    <div class="uk-modal-dialog uk-flex uk-flex-center uk-flex-middle" data-uk-height-viewport><button class="uk-modal-close-full" type="button" data-uk-close></button>
      <form class="uk-search uk-search-large"><input class="uk-search-input uk-text-center" type="search" placeholder="Search..." aria-label="None" autofocus></form>
    </div>
  </div>
</footer>

app/views/shared/_header-home.html.erb
<header class="page-header">
  <div class="page-header__top">
    <div class="uk-container">
      <nav class="uk-navbar-container uk-navbar-transparent" data-uk-navbar="">
        <div class="uk-navbar-left"><button class="uk-button" type="button" data-target="#offcanvas" data-uk-toggle data-uk-icon="menu"></button>
          <ul class="uk-navbar-nav">
            <li><a href="<%= root_path %>">Home</a></li>
            <li><a href="<%= pages_path %>">Order Online</a></li>
          </ul>
        </div>
        <div class="uk-navbar-center">
          <div class="logo">
            <div class="logo__box"><a class="logo__link" href="<%= root_path %>"><%= image_tag("logo.png", :alt => "logo", class: "logo__img logo__img--full") %></a></div>
          </div>
        </div>
        <div class="uk-navbar-right">
          <ul class="uk-navbar-nav">
            <li><a href="<%= pages_path %>">Our Menu</a></li>
            <li><a href="<%= new_contact_path %>">Feedback</a></li>
            <li><a href="<%= contact_index_path %>">Contact us</a></li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
  <div class="page-header__bottom">
    <div class="uk-container">
      <div class="uk-navbar-container uk-navbar-transparent" data-uk-navbar="">
        <div class="uk-navbar-left">
          <div>
            <div class="block-with-phone"><%= image_tag("icons/delivery.png", :alt => "delivery")%>
              <div> <span>For Delivery, Call us</span><a href="tel:13205448749">1-320-544-8749</a></div>
            </div>
          </div>
        </div>
        <div class="uk-navbar-center"></div>
        <div class="uk-navbar-right">
          <div class="other-links">
            <a class="uk-button" href=<%=new_page_path %> > <span>Thanh toán</span></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header.html.erb
<header id="header" class="navbar navbar-expand-lg navbar-fixed navbar-height navbar-flush navbar-container navbar-bordered">
  <%= link_to "Đăng xuất", destroy_user_session_path, method: :delete%>
</header>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
      toastr['<%= type %>']('<%= value %>');
    <% end %>
  </script>
<% end %>

app/views/shared/_message_html.html.erb
<% flash.each do |name, msg| %>
  <% if msg.class == Array %>
    <% msg.each do |message| %>
      <%= content_tag :div, message, :id => "flash_#{name}" %>
    <% end %>
  <% else %>
    <%= content_tag :div, msg, :id => "flash_#{name}", class: "my-3 text-danger" %>
  <% end %>
<% end %>