config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  root to: "home#index"
  resources :restaurants
  resources :pages
  resources :contact
  resources :payment

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  belongs_to :restaurant

  has_many :order_foods
  has_many :orders, through: :order_foods

  mount_uploader :avatar, AvatarUploader
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :quantity, :price, :category_id, :restaurant_id, :avatar)
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">

      <div class="row form-group">
        <%= form.label :name, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.text_field :name, class: "form-control", placeholder: "Please input name", required: true %>
        </div>
      </div>

      <div class="row form-group">
        <%= form.label :avatar, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.file_field :avatar, class: "form-control" %>
        </div>
      </div>

      <div class="row form-group">
        <%= form.label :quantity, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.text_field :quantity, class: "form-control", placeholder: "Please input quantity (number)", required: true %>
        </div>
      </div>

      <div class="row form-group">
        <%= form.label :price, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.text_field :price, class: "form-control", placeholder: "Please input price ", required: true %>
        </div>
      </div>

      <div class="row form-group">
        <%= form.label :category_id, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.select :category_id, options_for_select(Category.all.collect{|a| [a.name, a.id]}, food.category.present? ? food.category.id : ""), {include_blank: "-- Please select category --"}, {class: "form-control", required: true} %>
        </div>
      </div>

      <div class="row form-group">
        <%= form.label :restaurant_id, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.select :restaurant_id, options_for_select(Restaurant.all.collect{|a| [a.name, a.id]}, food.restaurant.present? ? food.restaurant.id : ""), {include_blank: "-- Please select restaurant --"}, {class: "form-control", required: true} %>        </div>
      </div>

      <div class="d-flex justify-content-end">
        <%= form.submit "Save changes", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div class="page-header">
  <div class="row align-items-center mb-3">
    <div class="col-sm mb-2 mb-sm-0">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-no-gutter">
          <li class="breadcrumb-item"><a class="breadcrumb-link" href="<%= root_path %>"><%= fa_icon("home") %></a></li>
          <li class="breadcrumb-item active" aria-current="page">Foods</li>
        </ol>
      </nav>

      <h1 class="page-header-title">Foods<span class="badge badge-soft-dark ml-2"><%= Food.all.size %></span></h1>
    </div>
    <div class="col-sm-auto">
      <%= link_to "Add Food", new_food_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="card">
  <div class="table-responsive">
    <table class="table table-borderless card-table">
      <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>quantity</th>
        <th>Price</th>
        <th>Category</th>
        <th>Restaurant</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.id %></td>
          <td>
            <%= image_tag food.avatar.url, width: "80px" if food.avatar.present? %>
            <%= food.name %>
          </td>
          <td><%= food.quantity %></td>
          <td><%= food.price %></td>
          <td><%= food.category.name if food.category.present? %></td>
          <td><%= food.restaurant.name if food.restaurant.present? %></td>
          <td><%= link_to 'Show', food %></td>
          <td><%= link_to 'Edit', edit_food_path(food) %></td>
          <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @food.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @food.category_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @food.restaurant_id %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>