config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :customers
  resources :foods
  resources :categories
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
  root to: "home#index"
  resources :restaurants
  resources :pages
  resources :contact
  resources :payment

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  belongs_to :restaurant

  has_many :order_foods
  has_many :orders, through: :order_foods

  mount_uploader :avatar, AvatarUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer

  has_many :order_foods
  has_many :foods, through: :order_foods
end

app/models/order_food.rb
class OrderFood < ApplicationRecord
  belongs_to :order
  belongs_to :food
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role: { user: 0, admin: 1, moderator: 2, editor: 3, vip: 4, banned: 5 }
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  layout 'home'
  def index
  end

  def new
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: %i[ show edit update destroy ]

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :quantity, :price, :category_id, :restaurant_id, :avatar)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    update_from_param(params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    update_from_param(params)
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

    # Use callbacks to share common setup or constraints between actions.
  def set_order
      @order = Order.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def order_params
      params.require(:order).permit(:customer_id, :total_price, :quantity)
  end

  def update_from_param(params)
    food_ids = params[:order][:food_ids].reject(&:blank?)
    foods = Food.where(id: food_ids)
    @order.foods = foods

    # food_ids.each do |food_id|
    # order_food = OrderFood.where(order_id: @order.id, food_id: food_id).first_or_create
    #   order_food.quantity = 100
    #   order_food.total_price = 1000
    #   order_food.save
    # end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  layout 'home'
  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
  end
end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController

  layout 'home'
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_restaurant, only: %i[ show edit update destroy ]


  def home
  end
  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">

      <div class="row form-group">
        <%= form.label :name, class: "col-sm-2 col-form-label input-label" %>
        <div class="col-sm-10">
          <%= form.text_field :name, class: "form-control", placeholder: "Please input name", required: true %>
        </div>
      </div>

      <div class="d-flex justify-content-end">
        <%= form.submit "Save changes", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="page-header">
  <div class="row align-items-center mb-3">
    <div class="col-sm mb-2 mb-sm-0">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb breadcrumb-no-gutter">
          <li class="breadcrumb-item"><a class="breadcrumb-link" href="<%= root_path %>"><%= fa_icon("home") %></a></li>
          <li class="breadcrumb-item active" aria-current="page">Restaurants</li>
        </ol>
      </nav>

      <h1 class="page-header-title">Restaurants <span class="badge badge-soft-dark ml-2"><%= Restaurant.all.size %></span></h1>
    </div>
    <div class="col-sm-auto">
      <%= link_to "Add Restaurant", new_restaurant_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="card">
  <div class="table-responsive">
    <table class="table table-borderless card-table">
      <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td><%= restaurant.id %></td>
          <td><%= restaurant.name %></td>
          <td><%= link_to 'Show', restaurant %></td>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>